package org.rebeam.tree.view.sortable

/**
  * A permutation generated by dragging an item from one index to another
 *
  * @param oldIndex The item's old index
  * @param newIndex The item's new index
  */
case class Permutation(oldIndex: Int, newIndex: Int)
